name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 23
          maven-version: 3.9.1

      - name: Setup Maven Settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "maven-central", "username": "${{secrets.MAVEN_USERNAME}}", "password": "${{secrets.MAVEN_PASSWORD}}"}]'

      - name: Extract version from tag
        id: extract_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean verify
        working-directory: parquet4j
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Package with Maven
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }} && mvn package -DskipTests
        working-directory: parquet4j

      - name: Deploy Github and Maven Central
        run: mvn deploy
        working-directory: parquet4j
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}